# Generated by Django 6.0 on 2025-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saderatBankHealthMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saderatbankhealthmonitoring',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
