# Generated by Django 6.1.1 on 2026-09-22 17:12

import django.db.models.deletion
import saderatBankHealthMonitoring.schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saderatBankHealthMonitoring', '0004_monitoringtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtype',
            name='field_schema',
            field=models.JSONField(blank=True, default=dict, validators=[saderatBankHealthMonitoring.schema.validate_field_schema]),
        ),
        migrations.CreateModel(
            name='PatientEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=10)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='saderatBankHealthMonitoring.saderatbankhealthmonitoring')),
            ],
            options={
                'ordering': ['national_id'],
            },
        ),
        migrations.CreateModel(
            name='PatientEntryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(max_length=512, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='saderatBankHealthMonitoring.patiententry')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patiententry',
            constraint=models.UniqueConstraint(fields=('monitoring', 'national_id'), name='unique_entry_monitoring_national_id'),
        ),
    ]
